CREATE DATABASE CICLISMO;
use CICLISMO;
CREATE TABLE Bicicleta (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(100) NOT NULL,
    precio VARCHAR(15) NOT NULL
);
SHOW TABLES;
describe Bicicleta;
